# Generated by Django 3.2.6 on 2022-02-03 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_preregistration_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreRegistration',
        ),
    ]
