# Generated by Django 3.2.6 on 2022-02-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_delete_preregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('password1', models.CharField(max_length=40)),
                ('password2', models.CharField(max_length=40)),
            ],
        ),
    ]
