# Generated by Django 3.2.6 on 2022-02-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_preregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='otp',
            field=models.CharField(default='DEFAULT VALUE', max_length=10),
        ),
    ]
