# Generated by Django 3.2.6 on 2022-02-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
