# Generated by Django 3.2.8 on 2022-02-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_auto_20220228_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='zip_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
